// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAATCwbbbs25fwIABpq4OnJMq17K2JGY1M',
    appId: '1:774441679128:web:51f1bee175833fbd2e066d',
    messagingSenderId: '774441679128',
    projectId: 'law-office-management-sy-37891',
    authDomain: 'law-office-management-sy-37891.firebaseapp.com',
    storageBucket: 'law-office-management-sy-37891.firebasestorage.app',
    measurementId: 'G-W004XFK7F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_1cDl3T7-iwCHUiMZOKE3nDmlq83cI2U',
    appId: '1:774441679128:android:003890894bea9e3d2e066d',
    messagingSenderId: '774441679128',
    projectId: 'law-office-management-sy-37891',
    storageBucket: 'law-office-management-sy-37891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwjlpWCUyI59wcLYDKrCSXd_PJRyzfgNw',
    appId: '1:774441679128:ios:68d3e9d0791f89722e066d',
    messagingSenderId: '774441679128',
    projectId: 'law-office-management-sy-37891',
    storageBucket: 'law-office-management-sy-37891.firebasestorage.app',
    iosClientId: '774441679128-4oib10na4i96ik7mcj64q5hrv7cpha6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawofficemanagementsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwjlpWCUyI59wcLYDKrCSXd_PJRyzfgNw',
    appId: '1:774441679128:ios:68d3e9d0791f89722e066d',
    messagingSenderId: '774441679128',
    projectId: 'law-office-management-sy-37891',
    storageBucket: 'law-office-management-sy-37891.firebasestorage.app',
    iosClientId: '774441679128-4oib10na4i96ik7mcj64q5hrv7cpha6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawofficemanagementsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAATCwbbbs25fwIABpq4OnJMq17K2JGY1M',
    appId: '1:774441679128:web:606c653b711a037b2e066d',
    messagingSenderId: '774441679128',
    projectId: 'law-office-management-sy-37891',
    authDomain: 'law-office-management-sy-37891.firebaseapp.com',
    storageBucket: 'law-office-management-sy-37891.firebasestorage.app',
    measurementId: 'G-J3YFQ7V244',
  );

}